language: node_js
node_js:
- node
cache:
  directories:
  - node_modules
before_deploy:
- sudo chown -R $(whoami) /usr/local/bin/
- curl -sf https://up.apex.sh/install | sh
- up upgrade
deploy:
- provider: script
  script: up deploy
  skip_cleanup: true
  on:
    branch: dev
- provider: script
  script: up deploy staging
  skip_cleanup: true
  on:
    branch: master
    tags: false
- provider: script
  script: up deploy production
  skip_cleanup: true
  on:
    branch: master
    tags: true
env:
  global:
  - AWS_REGION: us-west-2
  - secure: P++Ok+Uxoq181R7d0Cgr5DVQ0APYHkenyoDPPkicN6xcIh0eRet1vjUfhqOVjSgrUeQYyKh8ftdOw9657sRsnbrODRDIztFVuFGlzqQva5/XxM/OaOt1FTQ2PK61qQQvQy07pYyUxYOexxqIOslUwwPvL9FrT6+e871LO42TEz59bi67SMa8jKXH++NpXnQqwIwFRsfewDF4rBHKAO0acfV3um3SXSM/RIakAg61MKEHh4Lkg2deL/zag75w5kjCIu/6fxJjeG4InpRAkmXYieRic5XjrRMZIWQpbnxBvwo6kFo/m68XS94ynGlAxfiWHxvJJigI+6hWWrHjbDPOG03hjvUvfyaBfod56lr/leVk8kwE3UrU0fzTgf8Bp8cVYJlCVAC+MEaLEX4pxK3bdkBEjnvdwDlKrOqsCkOl5BvMXW/HhLHfO8i+WpaDzEn6PS0IlyATt86+h0y2c2WrmAmrMET8HV8S2hAL8m+F1l4bXAbW22kee93TfTX3fhii4qkFxKfQX2QbfcqOMjdrkb6z1WQ1zq67agIaDIXGV38CmOW/XerxM1/1hRAeEx2bWafmL/307uDC1m3Oa97vAlFaHLprb1xkY+MLDKJQ3PrCSoJ7tGuZhPDZK6ENjwoVfRS/w2LUqGIPI6sJKf5jGu4JvAbEhwkdYUDWfbxRvjg=
  - secure: rBeBdS5xguDttmW/8dFsZ4UQrUdcunAKD0HPKIULYfbf1oWwc1lrGfeqQ98m5xp35DPWdrT9t9uc5kdOWuJbv0zQmzNn+jTiRMPtVdTPu3RB2jnATUcvG7AdsmvlIbOuC2HXEuyScSneoIpyTvoWIoanji9dYkXIXQrTJmNdElPPJUtK7CXkoxAZtSMD3MnClbEWHFPiIUVFK/mxW44gKGyekpz9UbkwJFUq1ik/wLhomUluDhWh15LDeMh9oPFy/cxPYBWAUNgj2HLkTzKCeU4vlmQHihZrxq/ScgUZq0GPjGQrbxunFacEk3CnekSNnJ8zSkA2PIgIO0BCB+ihd6tIa0zj1UXXu3E19eGkhKWfQPh6R3Qg0zW+GK9k5jiQeWTGVcwdW1RAlApRex8dy07d7ZXCHFMislKUs2MmlKbwHVHKdGxjgVfi353qG8YBW2udz1olFDsUc6mn6ia/rSar86EeWCAyY6toNqfLFGxYRWhwZ9KhL64Hop51mvNXPBpivd4LlF++XSAQ/Pjrfj/kqVSQJYHaYKiTwLVDNtVbCxqd7oMN0ZI34pGXrGatdKvyTiKJtptbkxfbaJ5rY0+jVxX2/w/JT44txAKGAjnaV4I7xmU5+RXcNPrvTatTGWAIKZQZsfYmQS33cKRoFV1qaOYagmUgfd1QMcftVkg=
  - secure: nypP57NFcl0fsDFB4a/KoNafDNLgm0Q6gQTD5Ka4w0l1DVODmiI+nplTlrJuwOV2npy2fqerBNmcnnLR4TpoM7tCZdFCtX2O6pFigPqxIKNzaiX1hWiDocJ6jT89YWG1ZDAfJjKP+1GD2Qvd9MJwpHUo6GLWlgfncDkw73gQAFVbgNJBZc1+nWjm6WCRQzfaWqUiw/59XaYfC5UmFM6wtPXl3tsZDm296ik5kmZecpqbU9BQzcExZfmwCOhQVo+y5Q31w4pE/2lOu4EuApl2jcnkRcrXgAZyTRdxzHkbglHwooTzxpQ6cN3h9pXVaK1S3Y6MiFhUO8fhse+/Z+YCK4lSunjD2LkRidmquKmLRLFw7nYYugaeZ/FHEQmIx75qKOI33vrP+o/Usmu++Hg9+AuctYF4CDmWLBR6zRiOjs2p+9+Ja3m6p8Rp0eTiaU7cVSOy99ig2jLnImpnwjwumsGS+PTTFyciB1vtDZrtdB2Kpl5eT/bD/vlo1WomQwfYUurppxKU8pqMZaveVfCazZePoibcC4IFMnilcJuMz30ParWAy+jFuPsuQxfrOBlV9RswXz3FoGBedXRxuF9tH1iXFPyiqsDos3gsNAzULALYyZy5yVl40WEEEPoXi0HNcIqZGROztHxX/xi+bS6cXHe3lv6fqTnbfXv1Iqt4FSg=
